host: https://www.commcarehq.org
domain: co-carecoordination-perf
build_id: b62974969e57051ad70160a798ed79e8
app_id: 3271c8c86a5344e59554dfcb3e4628b8
#  b62974969e57051ad70160a798ed79e8
domain_user_credential: LocustScripts/update-scripts/project-config/co-carecoordination-perf/mobile_worker_credentials.json
owner_id: 3ca0fb9a3402487590f9b2eb5f0c876e
app_config_bed_tracking_tool: LocustScripts/update-scripts/project-config/co-carecoordination-perf/app_config_bed_tracking_tool.json
