# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ CCHQ_Smoke_Test ]
  pull_request:
    branches: [ CCHQ_Smoke_Test ] 
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r HQSmokeTests/requires.txt
        export DISPLAY=mymachine.com:0.0
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: CCHQ Smoke Test with pytest
      env:
        DIMAGIQA_URL: ${{ secrets.DIMAGIQA_URL }}
        DIMAGIQA_LOGIN_USERNAME: ${{ secrets.DIMAGIQA_LOGIN_USERNAME }}
        DIMAGIQA_LOGIN_PASSWORD: ${{ secrets.DIMAGIQA_LOGIN_PASSWORD }}
      run: |
        pytest -v --reruns 2 --capture=tee-sys
    - name: Archive test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-result-report
        path: /home/runner/work/dimagi-qa/dimagi-qa/HQSmokeTests/report.html
        retention-days: 2
