name: Cypress Tests

on:
  push:
    branches: [ master1 ]
  pull_request:
    branches: [ master1 ]
#  repository_dispatch:
#    types: [ deploy_success ]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: FormplayerTests
          record: true
          spec: ./cypress/integration/testCases/*
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          CYPRESS_QA_URL: ${{ secrets.DIMAGIQA_URL }}
          CYPRESS_LOGIN_USERNAME: ${{ secrets.DIMAGIQA_LOGIN_USERNAME }}
          CYPRESS_LOGIN_PASSWORD: ${{ secrets.DIMAGIQA_LOGIN_PASSWORD }}

      - name: Cypress test results
        uses: actions/upload-artifact@v2
        with:
          name: test-run-videos
          path: /home/runner/work/dimagi-qa/dimagi-qa/FormplayerTests/cypress/videos/testCases/*
          retention-days: 2
