name: Capture metrics on Datadog

on:
  workflow_run:
    workflows:
      - HQ Smoke Tests
    types:
      - completed
    branches: [ master, kt/new2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 21
    steps:
      - uses: int128/datadog-actions-metrics@v1
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}