# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ deploy_success ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r HQSmokeTests/requires.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: CCHQ Smoke Test with pytest
      env:
        DIMAGIQA_ENV: ${{ github.event.client_payload.environment }}  #${{ secrets.DIMAGIQA_URL }}
        DIMAGIQA_LOGIN_USERNAME: ${{ secrets.DIMAGIQA_LOGIN_USERNAME }}
        DIMAGIQA_LOGIN_PASSWORD: ${{ secrets.DIMAGIQA_LOGIN_PASSWORD }}
        DIMAGIQA_MAIL_USERNAME: ${{ secrets.DIMAGIQA_MAIL_USERNAME }}
        DIMAGIQA_MAIL_PASSWORD: ${{ secrets.DIMAGIQA_MAIL_PASSWORD }}
        RUN_NUMBER: ${{github.run_number}}
        
      run: |
        echo "client_payload: ${{ toJson(github.event.client_payload) }}"
        pytest -v --reruns 2 --capture=tee-sys --html=report.html --self-contained-html
        echo "NOW=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo ${{env.NOW}}
    - name: Send Pass Email
      uses: dawidd6/action-send-mail@v3
      if: success()   
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        # Required mail subject:
        subject: ${{ github.event.client_payload.environment }}  PASS - Github Actions job result ${{env.NOW}}  #${{github.run_number}}
        # Required recipients' addresses:
        to: qa@dimagi.com
        # Required sender full name (address can be skipped):
        from: <no-reply@dimagi.com> # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        html_body: file:////home/runner/work/dimagi-qa/dimagi-qa/HQSmokeTests/email_pass.html
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: normal
    - name: Send Failure Email
      uses: dawidd6/action-send-mail@v3
      if: failure()   
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        # Required mail subject:
        subject: ${{ github.event.client_payload.environment }} FAIL - Github Actions job result ${{env.NOW}}  #${{github.run_number}}
        # Required recipients' addresses:
        to: qa@dimagi.com
        # Required sender full name (address can be skipped):
        from: <no-reply@dimagi.com> # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed with failure!
        # Optional HTML body read from file:
        html_body: file:////home/runner/work/dimagi-qa/dimagi-qa/HQSmokeTests/email_fail.html
        # Optional attachments:
        attachments: /home/runner/work/dimagi-qa/dimagi-qa/report.html
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: normal
    - name: Archive test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-result-report
        path: /home/runner/work/dimagi-qa/dimagi-qa/report.html
        retention-days: 2
